config/routes.rb
Rails.application.routes.draw do
	root 'home#index'
	get :home, controller: :home, action: :index

	devise_for :users

	namespace :api, format: :json do
		resources :users, only: :index do
			collection do
				get :role, path: '/by_role/:role'
				get :inactive
			end
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	devise :database_authenticatable, :registerable
	enum role: %w[ user admin ]
end

app/controllers/api/users_controller.rb
module Api
	class UsersController < ApplicationController
		before_action :authenticate_user!

		def index
			render json: User.all
		end

		def role
			current_role = User.roles[ params[ :role ] ]
			render json: User.where( role: current_role )
		end

		def inactive
			render json: User.where( active: false )
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
.index
	- 150.times do |i|
		h1
			| Lorem ipsum&nbsp;
			= i
			| !

app/views/layouts/application.html.slim
doctype html
html
	head
		title Testapp

		meta name="viewport" content="width=device-width, initial-scale=1.0"

		= stylesheet_link_tag    'application', media: 'all'
		= javascript_include_tag 'application'
		= csrf_meta_tags

	body
		.body
			- if current_user
				header
					h1.page-title
				nav = render 'templates/sidebar'
			.content = yield

app/views/templates/_sidebar.html.slim
.sidebar
	= link_to 'Домой', '/', class: 'link'
	= link_to 'Все пользователи', :api_users, class: 'link xhr'
	= link_to 'Администраторы', role_api_users_path(:admin), class: 'link xhr'
	= link_to 'Пользователи', role_api_users_path(:user), class: 'link xhr'
	= link_to 'Неактивные пользователи', :inactive_api_users, class: 'link xhr'